### ISSUE TITLE
Make metadata-listener a gem

### ISSUE THREAD

**Issue by awead** [psu-libraries/metadata-listener#15]
There are some pros and cons to this, so there needs to be some discussion. So I'll lay them out here and we can discuss.

# Pros

1. Loading up files should be easier since everything is in $GEM_PATH
  a. Sidekiq is easily started with a simple `require 'metadata_listener'` instead of loading each file within the lib directory
  b. You can also load up the application in console via `bundle console` the same way
2. We can declare development dependencies such as RSpec, Pry and others
3. We can create a versioned dependency between a consuming application like Scholarsphere by releasing version 1.0 of metadata_listener and adding it to Scholarsphere's gemfile
  a. Because of this, Scholarsphere can call `MetadataListener::Job` directly instead of having to have an identically-named job in its own `app/jobs`

# Cons

1. Consuming applications, like Scholarsphere, would have to satisfy the gem's runtime dependencies. This is kind of annoying because if we want to use a gem in metadata_listener to do things, that gem would also have to install correctly in Scholarphere, even if we're never, ever going to use it there.
2. The declared version dependency isn't _really_ what we're trying to do because the SS4 and the gem aren't really dependent on one another, they just have to be compatible together

**Comment by rschenk** [comment]
I must admit, I'm not totally stoked on the gem idea. Maybe my thinking is too uptight. Am I correct in thinking that the problem that we're trying to solve is ensuring we've got the right version of metadata-listener running against the corresponding version of ScholarSphere? If that's the case, then how does the gem solve it? ScholarSphere can specify a version of the metadata-listener in its gemfile, but that doesn't affect or influence the metadata-listener worker machines that are spun up on separate machines, right?  Those are a separate deploy from the metadata-listener repo?

**Comment by awead** [comment]
@rschenk Agreed. There's also the problem that gems don't have their dependencies spelled out in a Gemfile.lock file. So I don't think this is answer we're looking for. Basically, we want to be able to mandate that Scholarsphere 4.0 must work with only MetadataListener 1.0 and be assured that when those worker machines do spin up, they're using 1.0. We can tag 1.0 releases of metadata-listener, then I guess it's up to the orchestrator (kubernetes, etc.) to enforce that.

**Comment by rschenk** [comment]
@awead Is that actually true though?  What if we come up with a better virus scanning option, and release MetadatListener 1.1? It will still work with Scholarsphere 4.0 as long as it uses the same API

**Comment by awead** [comment]
True, if we have an API defined, which we really don't at this point. It's kind of an implicit agreement that I'll used the same-named job as you do and send you parameters that you can understand. If it were a true REST API, I'd have more faith in that assertion.
