### ISSUE TITLE
Use .ruby-version

### ISSUE THREAD

**Issue by awead** [psu-libraries/metadata-listener#7]
The Dockerfile is specifying the ruby version, but local dev might need a .ruby-version file to do this instead. Is there a way Docker could get the required Ruby version from .ruby-version instead?

**Comment by whereismyjetpack** [comment]
There isn't really a good way to dynamically do that in a way that follows the .ruby-version pattern. When updating dockerfile, or ruby-version i've been just putting them in both places.

**Comment by awead** [comment]
Since the tests need to run inside the docker container, there's probably not much of a need to specify the ruby version for the local env. We can revisit this later if we need to.
